import {
  Archive,
  HardHat,
  Globe,
  Wrench,
  Gauge,
  Lock,
  FileText,
  RefreshCw,
  Building2,
  MoveUpRight,
  LucideIcon,
  Hexagon,
  Workflow,
  Bot,
  Plug,
  Database,
  AlertTriangle,
  Zap,
  Brain,
  BrainCircuit,
  CodeSquare,
  CloudOff,
  Activity,
  AlertCircle,
  Code,
  Shield,
  Rocket,
  HeartPulse,
  BarChart,
  MonitorSmartphone,
  Brush,
  Package,
  Bell,
  Fingerprint,
  RefreshCcw,
} from "lucide-react";

// Function to map string names to Lucide icon components
export const getIconComponent = (iconName: string): LucideIcon => {
  const IconComponent: Record<string, LucideIcon> = {
    Archive,
    Shield,
    Activity,
    HardHat,
    Globe,
    Wrench,
    Plug,
    Gauge,
    Lock,
    FileText,
    RefreshCw,
    Zap,
    Rocket,
    HeartPulse,
    Building2,
    BarChart,
    Code,
    Hexagon,
    Brain,
    Bot,
    MoveUpRight,
    BrainCircuit,
    AlertCircle,
    Workflow,
    Database,
    AlertTriangle,
    CodeSquare,
    CloudOff,
    MonitorSmartphone,
    Brush,
    Package,
    Bell,
    Fingerprint,
    RefreshCcw,
  };

  return IconComponent[iconName] || Code;
};
