import { ExpertiseItem } from "@/services/industry-experties/insdustry-experties";
import {
  Briefcase,
  Coins,
  Store,
  Home,
  Code,
  Heart,
  Car,
  Camera,
  Layers,
  Rocket,
  Handshake,
  Server,
  Dumbbell,
  Shirt,
  Bolt,
  Leaf,
  Truck,
  Icon as LucideIcon,
} from "lucide-react";

export const expertiseData: ExpertiseItem[] = [
  {
    icon: Coins,
    name: "Finance & Banking",
    bgColorClass: "bg-[#fff7e6]",
    textColorClass: "text-amber-800",
  },
  {
    icon: Store,
    name: "E-commerce",
    bgColorClass: "bg-[#e5ffe5]",
    textColorClass: "text-green-800",
  },
  {
    icon: Home,
    name: "Real Estate",
    bgColorClass: "bg-[#ffe5f9]",
    textColorClass: "text-pink-800",
  },
  {
    icon: Code,
    name: "Software",
    bgColorClass: "bg-[#e5f5ff]",
    textColorClass: "text-sky-800",
  },
  {
    icon: Heart,
    name: "Health & Fitness",
    bgColorClass: "bg-[#fff7e6]",
    textColorClass: "text-amber-800",
  },
  {
    icon: Car,
    name: "Automotive",
    bgColorClass: "bg-[#e5ffe5]",
    textColorClass: "text-green-800",
  },
  {
    icon: Camera,
    name: "Photo & Video",
    bgColorClass: "bg-[#ffe5f9]",
    textColorClass: "text-pink-800",
  },
  {
    icon: Briefcase,
    name: "Business",
    bgColorClass: "bg-[#e5f5ff]",
    textColorClass: "text-sky-800",
  },
  {
    icon: Rocket,
    name: "Startup",
    bgColorClass: "bg-[#fff7e6]",
    textColorClass: "text-amber-800",
  },
  {
    icon: Handshake,
    name: "Non-profit",
    bgColorClass: "bg-[#e5ffe5]",
    textColorClass: "text-green-800",
  },
  {
    icon: Server,
    name: "Govt. & Public Sector",
    bgColorClass: "bg-[#ffe5f9]",
    textColorClass: "text-pink-800",
  },
  {
    icon: Dumbbell,
    name: "Sports & Fitness",
    bgColorClass: "bg-[#e5f5ff]",
    textColorClass: "text-sky-800",
  },
  {
    icon: Shirt,
    name: "Fashion & Apparel",
    bgColorClass: "bg-[#fff7e6]",
    textColorClass: "text-amber-800",
  },
  {
    icon: Bolt,
    name: "Energy & Utilities",
    bgColorClass: "bg-[#e5ffe5]",
    textColorClass: "text-green-800",
  },
  {
    icon: Leaf,
    name: "Agriculture",
    bgColorClass: "bg-[#ffe5f9]",
    textColorClass: "text-pink-800",
  },
  {
    icon: Truck,
    name: "Logistics",
    bgColorClass: "bg-[#e5f5ff]",
    textColorClass: "text-sky-800",
  },
];
